In [144]:
# Importing the pandas library
import numpy as np
import pandas as pd

# loading the data
path = "C:\\Users\\Abdullah\\Desktop\\bbc-fulltext-and-category\\bbc-text.csv"
data = pd.read_csv(path)

In [145]:
import nltk
import re
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer 
from nltk.stem import WordNetLemmatizer 

In [146]:
# loading the stop words list, stemmer and lemmatizer
stop_words =  {'which', 'and', "that'll", 'have', 'now', 'our', 'herself', "don't", "mustn't", 'too', 'or', 'to', 'yours', 'what', "you'd", 'these', 'theirs', 'myself', "you'll", 'through', 'hasn', "you're", 't', 'where', 'mustn', "shouldn't", 'into', 'during', 'itself', 'can', 'y', 'his', 'after', 'any', 'be', 'she', 'was', 'ain', 'above', 'does', 'doing', 'between', 'some', "hasn't", "shan't", 'under', 'nor', 'her', "won't", 'further', 'has', "didn't", 'needn', "wouldn't", 'it', 'having', 'with', 'few', 'at', 'out', 'on', 'because', 'm', 'more', 'there', 'themselves', 'that', 'don', 'did', 'an', 'off', 'you', 'up', 's', 'haven', 'down', 're', 'a', 'didn', 'their', 'them', 'no', 'other', 'him', 'shan', 'until', 'very', "hadn't", 'me', 'how', 'such', 'ma', 'in', "weren't", 'my', 'just', 'against', 'this', 'own', 'should', 'if', 'yourselves', 'the', 'aren', 'd', 'here', 'before', 'ourselves', 'were', 'while', 'doesn', 'yourself', 'below', 'of', 'is', 'so', "couldn't", 'each', "needn't", 've', 'when', 'both', 'couldn', 'most', 'wouldn', 'by', 'll', "she's", 'as', 'we', 'won', 'isn', 'once', 'wasn', 'again', 'will', 'ours', 'o', "aren't", 'its', 'who', 'than', 'i', 'whom', "you've", 'hers', "it's", 'only', 'hadn', 'are', 'they', 'shouldn', 'for', "should've", 'those', 'himself', "doesn't", "isn't", 'mightn', "haven't", 'weren', 'all', 'am', 'but', 'same', 'then', 'from', 'why', 'do', "wasn't", 'he', 'about', 'not', "mightn't", 'your', 'had', 'over', 'been', 'being'}
print(stop_words)

{'such', 'just', 'am', 'as', 'had', 'some', 'doing', 'be', 'an', 'shan', 'above', "weren't", 'ma', "won't", 'into', 'about', 'itself', 'a', 'ours', 'were', 'his', 'by', 'haven', 'other', 'does', "isn't", "didn't", "mustn't", "shan't", 'wouldn', 'until', "wasn't", 'in', 'we', 'he', 'it', 'weren', 'she', 'hasn', "you've", 'having', 've', 'couldn', 'i', "doesn't", 're', 'isn', 'to', 'each', 'they', 'where', "hasn't", 'didn', 'yourselves', "don't", 'against', 'below', 'few', 'here', 'ain', 'himself', 'or', 'at', 'these', 'mightn', 'o', 'themselves', "needn't", 'again', 'most', 'mustn', "mightn't", 'her', 'more', 'y', 'won', 'then', 'how', 'our', 'this', 'its', 'only', 'when', "haven't", 'm', 'll', 'wasn', 'of', 'have', 'now', 'any', 'did', "you'd", 'ourselves', 'than', 'hadn', 'them', 'can', 'same', 'their', 'with', 'through', 'no', 't', "hadn't", "she's", 'those', 'not', 'if', 'during', 'are', 'theirs', 'that', "that'll", 'but', 'under', 'between', 'needn', "wouldn't", 'before', 'on', 'an

In [147]:
def process_words(text):
    # tokenize the text
    words = text.split()
    new_words_list = []
    
    for word in words:
        # only add words which are not stop words
        if word not in stop_words:
            new_words_list.append(word)
    
    # concatenate the string
    return " ".join(new_words_list)


def preprocess(text):
    # convert to lower case
    text = text.lower()
    
    # replace non-alphabets with null
    text = re.sub('[^a-zA-Z ]','',text)
    
    #remove stop words
    text = process_words(text)
    
    return text

In [148]:
sample = data['text'][3]

print("Sample Text before Pre-Processing:\n",sample)

Sample Text before Pre-Processing:
 yeading face newcastle in fa cup premiership side newcastle united face a trip to ryman premier league leaders yeading in the fa cup third round.  the game - arguably the highlight of the draw - is a potential money-spinner for non-league yeading  who beat slough in the second round. conference side exeter city  who knocked out doncaster on saturday  will travel to old trafford to meet holders manchester united in january. arsenal were drawn at home to stoke and chelsea will play host to scunthorpe. the only other non-league side in the draw are hinckley united  who held brentford to a goalless draw on sunday. they will meet league one leaders luton if they win their replay against martin allen s team at griffin park.  a number of premiership teams face difficult away games against championship sides on the weekend of 8/9 january. third-placed everton visit plymouth  liverpool travel to burnley  crystal palace go to sunderland  fulham face carling cu

In [149]:
pre_sample = preprocess(sample)
print("Sample Text after Pre-Processing:\n",pre_sample)

Sample Text after Pre-Processing:
 yeading face newcastle fa cup premiership side newcastle united face trip ryman premier league leaders yeading fa cup third round game arguably highlight draw potential moneyspinner nonleague yeading beat slough second round conference side exeter city knocked doncaster saturday travel old trafford meet holders manchester united january arsenal drawn home stoke chelsea play host scunthorpe nonleague side draw hinckley united held brentford goalless draw sunday meet league one leaders luton win replay martin allen team griffin park number premiership teams face difficult away games championship sides weekend january thirdplaced everton visit plymouth liverpool travel burnley crystal palace go sunderland fulham face carling cup semifinalists watford bolton meet ipswich aston villa drawn sheffield united premiership strugglers norwich blackburn west brom away west ham cardiff preston north end respectively southampton visit northampton already beaten lea

In [150]:
# apply preprocessing on entire dataset
x = data['text'].apply(lambda x:preprocess(x))
print(x[:1])

0    tv future hands viewers home theatre systems p...
Name: text, dtype: object


In [151]:
# convert the input text to suitable features
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

count_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer()

x_counts = count_vectorizer.fit_transform(x)
x_tfidf = tfidf_vectorizer.fit_transform(x)

In [152]:
new_x = x_counts

In [153]:
# create labels for target
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 


label_encoder = LabelEncoder()
y = label_encoder.fit_transform( data['category'] )
print("Label Encodings:",y)

Label Encodings: [4 0 3 ... 1 2 3]


In [154]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(new_x,y,test_size=0.15)
print("Size of Training data:",x_train.shape[0])
print("Size of Testing data:",x_test.shape[0])

Size of Training data: 1891
Size of Testing data: 334


In [155]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [156]:
nb_model = MultinomialNB()
logistic_model = LogisticRegression()
dec_tree_model = DecisionTreeClassifier()

In [157]:
# training the model
nb_model.fit(x_train,y_train)
logistic_model.fit(x_train,y_train)
dec_tree_model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [158]:
def check_accuracy(model,x_test,y_test):
    total = x_test.shape[0]
    count =  0
    res = model.predict(x_test)
    for i in range(total):
        y_true = y_test[i]
        if y_true == res[i]:
            count+=1
    return count/total

print("Naive Bayes Accuracy:",check_accuracy(nb_model,x_test,y_test))
print("Logistic Regression Accuracy:",check_accuracy(logistic_model,x_test,y_test))
print("Desicion Tree Accuracy:",check_accuracy(dec_tree_model,x_test,y_test))

Naive Bayes Accuracy: 0.9700598802395209
Logistic Regression Accuracy: 0.9790419161676647
Desicion Tree Accuracy: 0.8622754491017964


In [159]:
sample_data = "actor injured while shooting and the movie got cancelled"
processed_data = preprocess(sample_data)
x_sample = count_vectorizer.transform([processed_data])

# get results
nb_result =  nb_model.predict(x_sample)
log_result = logistic_model.predict(x_sample)
tree_result = dec_tree_model.predict(x_sample)

# get labels
nb_result = label_encoder.inverse_transform(nb_result)
log_result = label_encoder.inverse_transform(log_result)
tree_result = label_encoder.inverse_transform(tree_result)

print("Naive Bayes Result:",nb_result)
print("Logistic Regession Result:",log_result)
print("Decision Tree Result:",tree_result)

Naive Bayes Result: ['entertainment']
Logistic Regession Result: ['sport']
Decision Tree Result: ['sport']


In [160]:
input_shape = x_train[0].shape[1]
output_shape = 5
print("Input Shape:",input_shape)
print("Output Shape:",output_shape)

Input Shape: 30174
Output Shape: 5


In [161]:
#create one hot encoding's for the labels
onehotencoder = OneHotEncoder() 
onehotencoder.fit(y.reshape(-1, 1))
labels = onehotencoder.transform(y.reshape(-1, 1)).toarray()
print("One hot Vector:\n",labels)

One hot Vector:
 [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [162]:
x_train, x_test, y_train, y_test = train_test_split(new_x,labels,test_size=0.15)


In [163]:
# import library
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [164]:
model = Sequential()
model.add(Dense( 1024 , activation='sigmoid',  input_dim = input_shape  ))
model.add(Dropout(0.2))
model.add(Dense( 512  , activation='sigmoid' ))
model.add(Dropout(0.2))
model.add(Dense( 256   , activation='sigmoid'))
model.add(Dropout(0.2))
model.add(Dense(128   , activation='sigmoid'))
model.add(Dropout(0.2))
model.add(Dense( 64   , activation='sigmoid'))
model.add(Dropout(0.2))
model.add(Dense( 5, activation='softmax'))

In [165]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 1024)              30899200  
_________________________________________________________________
dropout_21 (Dropout)         (None, 1024)              0         
_________________________________________________________________
dense_26 (Dense)             (None, 512)               524800    
_________________________________________________________________
dropout_22 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_27 (Dense)             (None, 256)               131328    
_________________________________________________________________
dropout_23 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_28 (Dense)             (None, 128)              

In [166]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
history = model.fit(x_train,y_train, epochs = 10, batch_size=32, validation_data = (x_test,y_test)  )

Train on 1891 samples, validate on 334 samples
Epoch 1/10
1891/1891 [==============================] - 82s 43ms/step - loss: 1.5824 - accuracy: 0.2734 - val_loss: 1.1938 - val_accuracy: 0.6976
Epoch 2/10
1824/1891 [===========================>..] - ETA: 1s - loss: 0.7272 - accuracy: 0.8218

In [ ]:
import matplotlib.pyplot as plt
h = history
plt.plot(h.history['accuracy'])
plt.plot(h.history['val_accuracy'])
plt.title('Model accuracy')
plt.show()

plt.plot(h.history['loss'])
plt.plot(h.history['val_loss'])
plt.title('Model Loss')
plt.show()

In [ ]:
sample_data = "actor injured while shooting and the movie got cancelled"
processed_data = preprocess(sample_data)
x_sample = count_vectorizer.transform([processed_data])

# get results
model_result = list(model.predict(x_sample)[0])

print(model_result)

# get labels
max_ = max(model_result)
index = model_result.index(max_)
result = label_encoder.inverse_transform([index])

print("Model Result:",result)